services:
  bot:
    image: hcr.io/disgoorg/disgo-butler/bot
    restart: unless-stopped
    volumes:
      - ./config.json:/opt/bot/config.json
    command: --sync-commands=true
    networks:
      - bot

networks:
  bot: